name: Trigger Netlify Build
on:
  schedule:
    # Every 20 minutes
    - cron: "0 2-22/4 * * *"
jobs:
  build:
    name: Netlify build
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f71c6dc0bbae8ced02327f8
